import type { Bet } from "@/lib/types";

export const betsData: Bet[] = [
  {
    id: "1",
    date: "2026-04-15",
    sport: "MLB",
    game: "Yankees vs Red Sox",
    betType: "Moneyline",
    selection: "Yankees",
    sportsbook: "DraftKings",
    odds: -120,
    stake: 50,
    toWin: 41.67,
    result: "pending",
    clv: 10,
    profit: 0,
  },
  {
    id: "2",
    date: "2026-04-14",
    sport: "NBA",
    game: "Lakers vs Warriors",
    betType: "Spread",
    selection: "Lakers -4.5",
    sportsbook: "FanDuel",
    odds: -110,
    stake: 40,
    toWin: 36.36,
    result: "win",
    clv: 8,
    profit: 36.36,
  },
  {
    id: "3",
    date: "2026-04-13",
    sport: "NFL",
    game: "Chiefs vs Bills",
    betType: "Total",
    selection: "Over 48.5",
    sportsbook: "BetMGM",
    odds: -105,
    stake: 25,
    toWin: 23.81,
    result: "loss",
    clv: -5,
    profit: -25,
  },
];

export const oddsData = [
  {
    id: "1",
    sport: "NBA",
    game: "Lakers vs Warriors",
    market: "Spread",
    sportsbook: "FanDuel",
    line: -4.5,
    odds: -110,
  },
  {
    id: "2",
    sport: "MLB",
    game: "Yankees vs Red Sox",
    market: "Moneyline",
    sportsbook: "DraftKings",
    line: -120,
    odds: -120,
  },
];

export const mockGameOdds = [
  {
    id: "1",
    sport: "NBA",
    game: "Lakers vs Warriors",
    homeTeam: "Lakers",
    awayTeam: "Warriors",
    sportsbook: "FanDuel",
    market: "spread",
    homeOdds: -110,
    awayOdds: -110,
    homeLine: -4.5,
    awayLine: 4.5,
    startTime: "2026-04-15T19:00:00Z",
  },
  {
    id: "2",
    sport: "MLB",
    game: "Yankees vs Red Sox",
    homeTeam: "Yankees",
    awayTeam: "Red Sox",
    sportsbook: "DraftKings",
    market: "moneyline",
    homeOdds: -120,
    awayOdds: 100,
    homeLine: -120,
    awayLine: 100,
    startTime: "2026-04-15T23:10:00Z",
  },
];

export const propsData = [
  {
    id: "1",
    player: "LeBron James",
    sport: "NBA",
    game: "Lakers vs Warriors",
    prop: "Points",
    line: 27.5,
    overOdds: -110,
    underOdds: -110,
    sportsbook: "FanDuel",
  },
  {
    id: "2",
    player: "Aaron Judge",
    sport: "MLB",
    game: "Yankees vs Red Sox",
    prop: "Home Runs",
    line: 0.5,
    overOdds: 300,
    underOdds: -400,
    sportsbook: "DraftKings",
  },
];

export const modelPredictions = [
  {
    id: "1",
    event: "Lakers vs Warriors",
    market: "Lakers -4.5",
    modelProbability: 0.58,
    impliedProbability: 0.5238,
    edge: 0.0562,
    recommendation: "Bet",
  },
  {
    id: "2",
    event: "Yankees vs Red Sox",
    market: "Yankees ML",
    modelProbability: 0.57,
    impliedProbability: 0.5455,
    edge: 0.0245,
    recommendation: "Lean",
  },
];
